param(
  [string]$BaseUrl = 'http://localhost:3000'
)

$ErrorActionPreference = 'Stop'
$baseUri = [Uri]$BaseUrl
if ($baseUri.Host -notin @('localhost', '127.0.0.1', '::1')) { throw "Local-only acceptance refused non-local BaseUrl: $BaseUrl" }
$root = Split-Path -Parent $PSScriptRoot
$checks = @(
  @{ file = 'site-structure-contract.mjs'; node = $true },
  @{ file = 'final-acceptance-matrix-contract.mjs'; node = $true },
  @{ file = 'hookah-additional-acceptance-contract.mjs'; node = $true },
  @{ file = 'visual-page-rules-contract.mjs'; node = $true },
  @{ file = 'visual-live-defects-contract.mjs'; node = $true },
  @{ file = 'dashboard-shift-deeplink-contract.mjs'; node = $true },
  @{ file = 'order-journal-display-contract.mjs'; node = $true },
  @{ file = 'finance-api-consistency-contract.mjs'; node = $true },
  @{ file = 'fold-responsive-contract.mjs'; node = $true },
  @{ file = 'sidebar-navigation-contract.mjs'; node = $true },
  @{ file = 'clients-editor-contract.mjs'; node = $true },
  @{ file = 'staff-active-count-contract.mjs'; node = $true },
  @{ file = 'dashboard-kpi-design-contract.mjs'; node = $true },
  @{ file = 'admin-section-heading-contract.mjs'; node = $true },
  @{ file = 'dashboard-shift-attribution-contract.mjs'; node = $true },
  @{ file = 'metrics-database-failclosed-contract.mjs'; node = $true },
  @{ file = 'header-shell-contract.mjs'; node = $true },
  @{ file = 'inventory-context-contract.mjs'; node = $true },
  @{ file = 'inventory-hierarchy-contract.mjs'; node = $true },
  @{ file = 'inventory-subdepartment-api-qa.mjs'; node = $true },
  @{ file = 'inventory-stock-status-qa.mjs'; node = $true },
  @{ file = 'inventory-stock-status-runtime-qa.mjs'; node = $true },
  @{ file = 'inventory-responsive-contract.mjs'; node = $true },
  @{ file = 'inventory-critical-state-qa.mjs'; node = $true },
  @{ file = 'inventory-premix-load-state-qa.mjs'; node = $true },
  @{ file = 'premix-batch-lifecycle-qa.mjs'; node = $true },
  @{ file = 'inventory-movement-transaction-qa.mjs'; node = $true },
  @{ file = 'directory-rename-runtime-qa.mjs'; node = $true },
  @{ file = 'demo-premix-unit-runtime-qa.mjs'; node = $true },
  @{ file = 'recipe-depletion-contract-qa.mjs'; node = $true },
  @{ file = 'recipe-depletion-runtime-qa.mjs'; node = $true },
  @{ file = 'recipe-depletion-pg-contract.mjs'; node = $true },
  @{ file = 'warehouse-qa.mjs'; node = $true },
  @{ file = 'tasks-qa.mjs'; node = $true },
  @{ file = 'mode-navigation-contract.mjs'; node = $true },
  @{ file = 'local-static-boundary.mjs'; node = $true },
  @{ file = 'local-click-contract.mjs'; node = $true },
  @{ file = 'pos-modal-a11y-contract.mjs'; node = $true },
  @{ file = 'staff-catalog-load-state-contract.mjs'; node = $true },
  @{ file = 'staff-catalog-refresh-runtime-qa.mjs'; node = $true },
  @{ file = 'local-design-contract.mjs'; node = $true },
  @{ file = 'local-deploy-contract.mjs'; node = $true },
  @{ file = 'security-default-credential-qa.mjs'; node = $true },
  @{ file = 'venue-timezone-validation-runtime-qa.mjs'; node = $true },
  @{ file = 'local-route-smoke.ps1'; args = @('-BaseUrl', $BaseUrl) },
  @{ file = 'local-role-contract.mjs'; node = $true },
  @{ file = 'role-api-matrix-runtime-qa.mjs'; node = $true },
  @{ file = 'finance-rbac-runtime-qa.mjs'; node = $true; standalone = $true },
  @{ file = 'finance-required-marker-contract.mjs'; node = $true },
  @{ file = 'finance-chart-empty-state-contract.mjs'; node = $true },
  @{ file = 'finance-load-race-qa.mjs'; node = $true },
    @{ file = 'finance-report-date-qa.mjs'; node = $true },
    @{ file = 'orders-total-qa.mjs'; node = $true },
    @{ file = 'orders-history-qa.mjs'; node = $true },
    @{ file = 'orders-receipt-qa.mjs'; node = $true },
    @{ file = 'delivery-persistence-qa.mjs'; node = $true },
    @{ file = 'delivery-ui-state-qa.mjs'; node = $true },
    @{ file = 'network-load-state-qa.mjs'; node = $true },
    @{ file = 'client-form-submit-qa.mjs'; node = $true },
    @{ file = 'client-form-race-qa.mjs'; node = $true },
    @{ file = 'reservation-form-qa.mjs'; node = $true },
    @{ file = 'inventory-form-pending-qa.mjs'; node = $true },
    @{ file = 'recipe-form-pending-qa.mjs'; node = $true },
    @{ file = 'premix-create-route-qa.mjs'; node = $true },
    @{ file = 'product-form-pending-qa.mjs'; node = $true },
    @{ file = 'purchase-document-pending-qa.mjs'; node = $true },
    @{ file = 'auto-order-pending-qa.mjs'; node = $true },
    @{ file = 'network-action-pending-qa.mjs'; node = $true },
    @{ file = 'portal-context-refresh-qa.mjs'; node = $true },
    @{ file = 'tobacco-catalog-demo-qa.mjs'; node = $true },
    @{ file = 'network-read-failure-qa.mjs'; node = $true },
    @{ file = 'network-mutation-boundary-qa.mjs'; node = $true },
    @{ file = 'network-selection-qa.mjs'; node = $true },
    @{ file = 'session-authority-qa.mjs'; node = $true },
    @{ file = 'portal-api-auth-qa.mjs'; node = $true },
    @{ file = 'network-patch-validation-qa.mjs'; node = $true },
  @{ file = 'local-insights-contract.mjs'; node = $true },
  @{ file = 'local-date-contract.mjs'; node = $true },
  @{ file = 'finance-timezone-contract.mjs'; node = $true },
  @{ file = 'finance-employee-contract.mjs'; node = $true },
  @{ file = 'local-asset-smoke.ps1'; args = @('-BaseUrl', $BaseUrl) },
  @{ file = 'local-login-contract.mjs'; node = $true },
  @{ file = 'login-error-runtime-qa.mjs'; node = $true },
  @{ file = 'staff-pin-passport-contract.mjs'; node = $true },
  @{ file = 'staff-pin-passport-runtime-qa.mjs'; node = $true },
  @{ file = 'staff-worklog-runtime-qa.mjs'; node = $true },
  @{ file = 'local-lock-contract.mjs'; node = $true },
  @{ file = 'local-preferences-contract.mjs'; node = $true },
  @{ file = 'local-saas-contract.mjs'; node = $true },
  @{ file = 'local-platform-organization-contract.mjs'; node = $true },
  @{ file = 'local-saas-onboarding-contract.mjs'; node = $true },
  @{ file = 'local-tea-catalog.ps1'; args = @('-BaseUrl', $BaseUrl) },
  @{ file = 'local-floor-management-contract.mjs'; node = $true },
  @{ file = 'integrations-scope-contract.mjs'; node = $true },
  @{ file = '..\smoke-test.ps1'; args = @('-BaseUrl', $BaseUrl) },
  @{ file = 'local-crud-contract.mjs'; node = $true },
  @{ file = 'local-guest-order.ps1'; args = @('-BaseUrl', $BaseUrl) },
  # Run local-100-orders.ps1 separately against a fresh isolated server. The production rate limit
  # intentionally applies to loopback too, and the full acceptance suite already exercises order CRUD.
  @{ file = 'payroll-qa.mjs'; node = $true },
  @{ file = 'payroll-calculation-qa.mjs'; node = $true },
  @{ file = 'payroll-lifecycle-runtime-qa.mjs'; node = $true },
  @{ file = 'payroll-register-ui-contract.mjs'; node = $true },
  @{ file = 'payroll-register-load-state-qa.mjs'; node = $true },
  @{ file = 'finance-categories-ui-contract.mjs'; node = $true },
  @{ file = 'finance-expense-payroll-status-contract.mjs'; node = $true },
  @{ file = 'payroll-lifecycle-migration-preflight.mjs'; node = $true },
  @{ file = 'postgres-qa-safety-contract.mjs'; node = $true },
  @{ file = 'purchase-payments-runtime-qa.mjs'; node = $true },
  @{ file = 'purchase-document-validation-qa.mjs'; node = $true },
  @{ file = 'purchase-document-date-contract.mjs'; node = $true },
  @{ file = 'purchase-payment-api-validation-qa.mjs'; node = $true },
  @{ file = 'purchase-payments-contract.mjs'; node = $true },
  @{ file = 'order-close-transaction-qa.mjs'; node = $true },
  @{ file = 'shift-transaction-qa.mjs'; node = $true },
  @{ file = 'shift-close-ui-qa.mjs'; node = $true },
  @{ file = 'migrations-contract.mjs'; node = $true },
  @{ file = 'order-attention-qa.mjs'; node = $true }
)
foreach ($check in $checks) {
  $path = Join-Path $PSScriptRoot $check.file
  if (-not (Test-Path $path)) { $path = Join-Path $root $check.file }
  Write-Output "RUN $($check.file)"
  if ($check.node -and $check.standalone) { & node $path }
  elseif ($check.node) { & node $path $BaseUrl }
  else { & pwsh -NoProfile -File $path @($check.args) }
  if ($LASTEXITCODE -ne 0) { throw "Acceptance check failed: $($check.file)" }
}
Write-Output 'LOCAL ACCEPTANCE: PASS (routes/assets, catalog, roles, staff, shifts, guest/order CRUD, payroll, supplier payments, migration contracts and delivery)'
